# Generated by Django 5.2 on 2025-04-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="full name"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="comment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100, verbose_name="topic")),
                ("message", models.TextField(verbose_name="message")),
            ],
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_for_sending",
                    models.DateTimeField(verbose_name="first mailing date"),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("day", "Каждый день"),
                            ("week", "Каждую неделю"),
                            ("month", "Каждый месяц"),
                        ],
                        default="week",
                        max_length=20,
                        verbose_name="periodicity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("started", "Запущена"),
                            ("failed", "Ошибка"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="mails",
                        to="client.client",
                        verbose_name="recipients",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.message",
                        verbose_name="message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified date"
                    ),
                ),
                (
                    "mail_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="mail response"
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt",
                        to="client.mail",
                        verbose_name="mail",
                    ),
                ),
            ],
        ),
    ]
