# Generated by Django 5.2 on 2025-04-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="title")),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="content"),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/", verbose_name="image"
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="views")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
        ),
    ]
